language: java
sudo: false
jdk:
  - oraclejdk17
before_script: cd apiconnector
script: mvn clean verify
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $AUTH
  on:
    branch: master
  local_dir: apiconnector/target/apidocs
name: Minion
after_success: mvn jacoco:report coveralls:report
